apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-object-detection-dummy-3
  janus-idp.io/tekton: test-object-detection-dummy-3
  backstage.io/kubernetes-id: test-object-detection-dummy-3
  backstage.io/kubernetes-namespace: ai-rhdh-app-development 
  app.kubernetes.io/part-of: test-object-detection-dummy-3
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
